apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: glovo
  description: The glovo organization
  links:
    - url: http://www.glovo.com/
      title: Website
spec:
  type: organization
  profile:
    displayName: Glovo
    email: info@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: clusters
  description: A collection of all glovo clusters
spec:
  targets:
    - ./platform-cluster.yaml
    - ./experimentation-team-group.yaml
